### ISSUE TITLE
Integration with PyQt5.

### ISSUE THREAD

**Issue by elixirphoenix** [jithurjacob/Windows-10-Toast-Notifications#10]
It seems like the program automatically exit after toast being run. Is there any way to sustain the application?

**Comment by rgkbitw** [comment]
It is a 'notifier' and hence it should not sustain for long.
But you can set time limit to be MAX to help yourself.

**Comment by elixirphoenix** [comment]
Sorry for misleading the topic. I meant it conflicts with PyQt5 loop and causes an application exit. Nevertheless, I've just found a way to solve this by using PyQt status bar and send toast via them instead.  Anyway, this is really good script when integrates to a small application without PyQt5 libraries.
