### ISSUE TITLE
UnregisterClass after DestroyWindow

### ISSUE THREAD

**Issue by openopentw** [jithurjacob/Windows-10-Toast-Notifications#11]
Add `UnregisterClass ` after `DestroyWindow` ([here](https://github.com/jithurjacob/Windows-10-Toast-Notifications/blob/master/win10toast/__init__.py#L107)).

Otherwise if I wrote a script like your [example](https://github.com/jithurjacob/Windows-10-Toast-Notifications#example) and exec it twice in python interpreter, there would be error messages saying that `class already exist`.

And that's because destroying the windows doesn't unregister the class.

**Comment by jithurjacob** [comment]
Hi @openopentw 
Sorry for the late response,I was caught up with work. Thank you for your interest in this project.

I've fixed the issue. Thank you for bringing this to my notice.
