### ISSUE TITLE
Only one class instance. 

### ISSUE THREAD

**Issue by rgkbitw** [jithurjacob/Windows-10-Toast-Notifications#13]
The class can not be instantiated for any other instance. 
It is not possible to have a second notifier instance running with different purpose.
`from win10toast import ToastNotifier as T`
`t1=T()  #instance 1`
`t2=T()  #instance 2`
Raises class already exists error.

**Comment by jithurjacob** [comment]
Hi @rgkbitw ,
Sorry for the late response,I was caught up with work. Thank you for your interest in this project.  

I have updated the package in Pypi. Could you please test and close the issue?
