### ISSUE TITLE
Dependency pywin32 not updated to pypiwin32 in PyPI

### ISSUE THREAD

**Issue by nikhil-97** [jithurjacob/Windows-10-Toast-Notifications#14]
When I try to `pip install win10toast` , I get the error message 

> Collecting pywin32 (from win10toast)
>   Could not find a version that satisfies the requirement pywin32 (from win10toast) (from versions: )
>No matching distribution found for pywin32 (from win10toast)

I guess it's becuase the version in PyPI has not been updated yet, to install pypiwin32, instead of pywin32.

**Comment by utopiacosmica** [comment]
Same problem.

**Comment by jithurjacob** [comment]
Hi @nikhil-97 @utopiacosmica 
Sorry for the late response,I was caught up with work. Thank you for your interest in this project.

I have updated the package in Pypi. Sorry for your inconvenience.
