### ISSUE TITLE
Not able to get any notification although the code runs with no errors

### ISSUE THREAD

**Issue by ravikd97** [jithurjacob/Windows-10-Toast-Notifications#21]

**Comment by jithurjacob** [comment]
Please check your windows settings to see if notifications are disabled

**Comment by ravikd97** [comment]
No I have checked .All notifications are allowed.

**Comment by jithurjacob** [comment]
Please check with your friend/colleague machine. This is most probably system setting issue

**Comment by nissansz** [comment]
How to adjust settings to enable it?
