### ISSUE TITLE
 Sometimes the notification does not appear and goes to the notification area

### ISSUE THREAD

**Issue by AlbertoSolaro** [jithurjacob/Windows-10-Toast-Notifications#43]
As a title sometimes the notification does not appear and goes directly into the notification area without sounding or appearing

![image](https://user-images.githubusercontent.com/9293308/45183834-7e760d00-b225-11e8-9e72-0bda09470ffd.png)

increases the notification counter and does not show it

**Comment by akk29** [comment]
Change the focus assistance in the settings of the windows to show all the notifications not only for Alarm

settings -> focus assist settings -> Get all notification from all apps 

BTW I think you are using dual screen monitor or more than one monitor that's why it is happening

**Comment by AlbertoSolaro** [comment]
Yes i use two monitor, thanks to answer me. I didn't known this option of win10 and i thought that the problem was related to the thread.
