### ISSUE TITLE
importing ToastNotifier from __main__ is very weird

### ISSUE THREAD

**Issue by eric-wieser** [jithurjacob/Windows-10-Toast-Notifications#5]
Would be much better to have this class either in `__init__.py` or its own file

This is especially weird because `__name__` is either `__main__` or `win10toast.__main__`

**Comment by jithurjacob** [comment]
I'm sorry but I didn't understand this. Could you please explain?

**Comment by eric-wieser** [comment]
Move `ToastNotifier` into `__init__.py`. It has no place in `__main__`.

**Comment by jithurjacob** [comment]
Thank you for your help fixed the issue
