### ISSUE TITLE
icon does not show up !

### ISSUE THREAD

**Issue by ShasV05** [jithurjacob/Windows-10-Toast-Notifications#77]
I have a home.ico image file in the same directory as my script but when I try to use it, it gives me an error.

Here is the error:

    ERROR:root:Some trouble with the icon (Path/path/path): (0, 'LoadImage', 'No error message is available')

Here is my code:

~~~~
from win10toast import ToastNotifier
import os
n = ToastNotifier()
basepath = os.getcwd()

def notify(title, message, dur):
    n.show_toast(title, message, duration=dur, icon_path=basepath+"\\icons\\home.ico")

notify("Hello","Hello",10)
~~~~

**Comment by william-kang** [comment]
Try using "./icons/home.ico" as your icon_path parameter instead.

**Comment by ShasV05** [comment]
Thanks , the icon wasn't valid though
