### ISSUE TITLE
Move if __name__ == __main__ to __main__.py

### ISSUE THREAD

**Issue by eric-wieser** [jithurjacob/Windows-10-Toast-Notifications#9]
[These lines](https://github.com/jithurjacob/Windows-10-Toast-Notifications/blob/master/win10toast/__init__.py#L122-L136)

Should be stripped of their surrounding if statement, and moved to `__main__.py`.

That way, the example can be run with `python -m win10toast`

**Comment by jithurjacob** [comment]
Done, thank you for your help. Please check the same

**Comment by eric-wieser** [comment]
Can you confirm it works with `python -m win10toast`?
